// AUTO-GENERATED FILE — do not edit by hand.
//
// Generated by scripts/build-sovereignty-data.mjs from the
// vendors/*.yaml files in the sovereignty-vendors submodule. Run
// `npm run prebuild` or edit a YAML + `node scripts/build-sovereignty-data.mjs`.
//
// Committing this file to the repo means the Vite config can import
// vendor data in Node context without needing import.meta.glob
// transforms.

import type { Vendor } from './sovereignty-types'

export const rawVendors: Vendor[] = [
  {
    "slug": "aws",
    "name": "Amazon Web Services",
    "category": "hosting",
    "contracting_entity": "Amazon Web Services EMEA SARL",
    "ultimate_parent": "Amazon.com, Inc.",
    "parent_jurisdiction": "US",
    "entity_jurisdiction": "EU",
    "hosting_regions": [
      "us-east-1",
      "us-west-2",
      "eu-central-1",
      "eu-west-1",
      "eu-west-3",
      "ap-southeast-1"
    ],
    "subprocessors": [],
    "eu_alternatives": [
      "scaleway",
      "hetzner",
      "ovhcloud"
    ],
    "transfer_mechanism": "SCCs+TIA",
    "operational_access_regions": [
      "US",
      "EU"
    ],
    "ratings": {
      "entity_control": "red",
      "data_location": "green",
      "operational_access": "amber",
      "subprocessor_chain": "green",
      "transfer_mechanism": "amber",
      "overall": "red"
    },
    "one_line_reason": "The EU-Luxembourg contracting entity is a subsidiary of Amazon.com, Inc. (US). CLOUD Act reach follows the ultimate parent — an EU subsidiary is not a jurisdictional firewall.\n",
    "sources": [
      "https://aws.amazon.com/compliance/eu-data-protection/",
      "https://aws.amazon.com/service-terms/",
      "https://d1.awsstatic.com/legal/aws-gdpr/AWS_GDPR_DPA.pdf"
    ],
    "last_reviewed": "2026-09-11",
    "notes": "AWS European Sovereign Cloud (announced 2023, launching in Brandenburg) may change this rating for that specific offering once GA and independent verification is possible.\n"
  },
  {
    "slug": "cloudflare",
    "name": "Cloudflare",
    "category": "cdn",
    "contracting_entity": "Cloudflare, Inc.",
    "ultimate_parent": "Cloudflare, Inc.",
    "parent_jurisdiction": "US",
    "entity_jurisdiction": "US",
    "hosting_regions": [
      "global-edge"
    ],
    "subprocessors": [],
    "eu_alternatives": [
      "bunny",
      "fastly-eu"
    ],
    "transfer_mechanism": "SCCs+TIA",
    "operational_access_regions": [
      "US",
      "EU",
      "SG"
    ],
    "ratings": {
      "entity_control": "red",
      "data_location": "amber",
      "operational_access": "amber",
      "subprocessor_chain": "green",
      "transfer_mechanism": "amber",
      "overall": "red"
    },
    "one_line_reason": "US-incorporated (Cloudflare, Inc.); the Data Localization Suite is a meaningful mitigation on the data-location + processing dimensions, but the parent-jurisdiction fact is unchanged and the CLOUD Act still reaches the entity. Overall red by the \"worst dimension wins\" rule.\n",
    "sources": [
      "https://www.cloudflare.com/trust-hub/gdpr/",
      "https://blog.cloudflare.com/data-localization-suite/",
      "https://www.cloudflare.com/cloudflare-customer-dpa/"
    ],
    "last_reviewed": "2026-09-11",
    "notes": "Cloudflare's Data Localization Suite is an amber-worthy mitigation for the data-location dimension but does not change the entity-control fundamental. Include the Suite pricing in any recommendation to a buyer who ends up here.\n"
  },
  {
    "slug": "eurobase",
    "name": "Eurobase",
    "category": "baas",
    "contracting_entity": "Eurobase OÜ",
    "ultimate_parent": "Eurobase OÜ",
    "parent_jurisdiction": "EU",
    "entity_jurisdiction": "EU",
    "hosting_regions": [
      "fr-par"
    ],
    "subprocessors": [
      "scaleway",
      "mollie"
    ],
    "eu_alternatives": [],
    "transfer_mechanism": "none",
    "operational_access_regions": [
      "EU"
    ],
    "ratings": {
      "entity_control": "green",
      "data_location": "green",
      "operational_access": "green",
      "subprocessor_chain": "green",
      "transfer_mechanism": "green",
      "overall": "green"
    },
    "one_line_reason": "Estonian OÜ, EU-hosted on Scaleway (France), EU payments via Mollie (Netherlands). No US entity, no US processor, no data transfer requiring SCCs or TIA.\n",
    "sources": [
      "https://eurobase.app/security",
      "https://eurobase.app/legal/dpa",
      "https://eurobase.app/pricing"
    ],
    "last_reviewed": "2026-09-11",
    "self_disclosure": true,
    "notes": "This dataset is maintained by Eurobase OÜ and Eurobase is graded here. The checker's UI must render a visible conflict-of-interest banner on this vendor page. If you are reviewing this rating and disagree, please open an issue — grading ourselves green while denying others the same grade would destroy the credibility of the dataset the first time someone noticed.\n"
  },
  {
    "slug": "firebase",
    "name": "Firebase",
    "category": "baas",
    "contracting_entity": "Google LLC",
    "ultimate_parent": "Alphabet Inc.",
    "parent_jurisdiction": "US",
    "entity_jurisdiction": "US",
    "hosting_regions": [
      "us-central1",
      "europe-west1",
      "europe-west3",
      "asia-northeast1",
      "southamerica-east1"
    ],
    "subprocessors": [
      "gcp"
    ],
    "eu_alternatives": [
      "eurobase",
      "appwrite"
    ],
    "transfer_mechanism": "DPF",
    "operational_access_regions": [
      "US",
      "IE",
      "IN"
    ],
    "ratings": {
      "entity_control": "red",
      "data_location": "amber",
      "operational_access": "red",
      "subprocessor_chain": "red",
      "transfer_mechanism": "amber",
      "overall": "red"
    },
    "one_line_reason": "Google LLC contracting entity, Alphabet parent, runs on GCP — a US hyperscaler that is itself a US-owned control plane. CLOUD Act reach is direct and unmitigated by region choice.\n",
    "sources": [
      "https://firebase.google.com/support/privacy",
      "https://cloud.google.com/terms/data-processing-addendum",
      "https://policies.google.com/privacy"
    ],
    "last_reviewed": "2026-09-11",
    "notes": null
  },
  {
    "slug": "gcp",
    "name": "Google Cloud Platform",
    "category": "hosting",
    "contracting_entity": "Google Ireland Limited",
    "ultimate_parent": "Alphabet Inc.",
    "parent_jurisdiction": "US",
    "entity_jurisdiction": "EU",
    "hosting_regions": [
      "us-central1",
      "us-east1",
      "europe-west1",
      "europe-west3",
      "europe-north1",
      "asia-northeast1"
    ],
    "subprocessors": [],
    "eu_alternatives": [
      "scaleway",
      "ovhcloud",
      "hetzner"
    ],
    "transfer_mechanism": "DPF",
    "operational_access_regions": [
      "US",
      "IE",
      "IN"
    ],
    "ratings": {
      "entity_control": "red",
      "data_location": "green",
      "operational_access": "amber",
      "subprocessor_chain": "green",
      "transfer_mechanism": "amber",
      "overall": "red"
    },
    "one_line_reason": "Google Ireland Limited signs the DPA but is a subsidiary of Alphabet Inc. (US). CLOUD Act applies to the parent, not the signing entity.\n",
    "sources": [
      "https://cloud.google.com/terms/data-processing-addendum",
      "https://cloud.google.com/privacy/gdpr",
      "https://policies.google.com/privacy"
    ],
    "last_reviewed": "2026-09-11",
    "notes": null
  },
  {
    "slug": "hetzner",
    "name": "Hetzner",
    "category": "hosting",
    "contracting_entity": "Hetzner Online GmbH",
    "ultimate_parent": "Hetzner Online GmbH",
    "parent_jurisdiction": "EU",
    "entity_jurisdiction": "EU",
    "hosting_regions": [
      "fsn1",
      "hel1",
      "nbg1",
      "hil"
    ],
    "subprocessors": [],
    "eu_alternatives": [],
    "transfer_mechanism": "none",
    "operational_access_regions": [
      "EU"
    ],
    "ratings": {
      "entity_control": "green",
      "data_location": "green",
      "operational_access": "green",
      "subprocessor_chain": "green",
      "transfer_mechanism": "green",
      "overall": "green"
    },
    "one_line_reason": "German GmbH, privately owned, datacentres in Germany and Finland. No US corporate control. Cloud, dedicated servers, and storage all covered.\n",
    "sources": [
      "https://www.hetzner.com/legal/privacy-policy",
      "https://www.hetzner.com/AV/DPA_en.pdf",
      "https://www.hetzner.com/unternehmen/impressum"
    ],
    "last_reviewed": "2026-09-11",
    "notes": "US datacenter in Hillsboro (hil) was added in 2024 for US customers. Any workload placed there loses the sovereignty benefit — the datacenter location matters for that region-specific service even though the contracting entity stays German.\n"
  },
  {
    "slug": "mollie",
    "name": "Mollie",
    "category": "payments",
    "contracting_entity": "Mollie B.V.",
    "ultimate_parent": "Mollie B.V.",
    "parent_jurisdiction": "EU",
    "entity_jurisdiction": "EU",
    "hosting_regions": [
      "nl-ams"
    ],
    "subprocessors": [],
    "eu_alternatives": [],
    "transfer_mechanism": "none",
    "operational_access_regions": [
      "EU"
    ],
    "ratings": {
      "entity_control": "green",
      "data_location": "green",
      "operational_access": "green",
      "subprocessor_chain": "green",
      "transfer_mechanism": "green",
      "overall": "green"
    },
    "one_line_reason": "Dutch B.V., privately owned, EU-hosted, EU-operated. Card + iDEAL + SEPA processing without a US payment schemes intermediary in the contract path.\n",
    "sources": [
      "https://www.mollie.com/legal/privacy",
      "https://www.mollie.com/legal/dpa",
      "https://www.mollie.com/en/about"
    ],
    "last_reviewed": "2026-09-11",
    "notes": null
  },
  {
    "slug": "scaleway",
    "name": "Scaleway",
    "category": "hosting",
    "contracting_entity": "Scaleway SAS",
    "ultimate_parent": "Iliad SA",
    "parent_jurisdiction": "EU",
    "entity_jurisdiction": "EU",
    "hosting_regions": [
      "fr-par",
      "nl-ams",
      "pl-waw"
    ],
    "subprocessors": [],
    "eu_alternatives": [],
    "transfer_mechanism": "none",
    "operational_access_regions": [
      "EU"
    ],
    "ratings": {
      "entity_control": "green",
      "data_location": "green",
      "operational_access": "green",
      "subprocessor_chain": "green",
      "transfer_mechanism": "green",
      "overall": "green"
    },
    "one_line_reason": "French SAS, ultimate parent Iliad (publicly listed on Euronext Paris), datacentres and operations in France, Netherlands, and Poland. No US corporate control anywhere in the chain.\n",
    "sources": [
      "https://www.scaleway.com/en/dpa/",
      "https://www.scaleway.com/en/security-and-compliance/",
      "https://www.scaleway.com/en/about/"
    ],
    "last_reviewed": "2026-09-11",
    "notes": null
  },
  {
    "slug": "stripe",
    "name": "Stripe",
    "category": "payments",
    "contracting_entity": "Stripe Payments Europe, Limited",
    "ultimate_parent": "Stripe, Inc.",
    "parent_jurisdiction": "US",
    "entity_jurisdiction": "EU",
    "hosting_regions": [
      "us-east",
      "us-west",
      "eu-west"
    ],
    "subprocessors": [
      "aws"
    ],
    "eu_alternatives": [
      "mollie",
      "adyen"
    ],
    "transfer_mechanism": "SCCs+TIA",
    "operational_access_regions": [
      "US",
      "IE"
    ],
    "ratings": {
      "entity_control": "red",
      "data_location": "amber",
      "operational_access": "red",
      "subprocessor_chain": "amber",
      "transfer_mechanism": "amber",
      "overall": "red"
    },
    "one_line_reason": "Stripe Payments Europe (Dublin) signs European customer contracts but is a subsidiary of Stripe, Inc. (Delaware). CLOUD Act reach applies to the parent.\n",
    "sources": [
      "https://stripe.com/legal/dpa",
      "https://stripe.com/legal/privacy-center",
      "https://stripe.com/legal/service-providers"
    ],
    "last_reviewed": "2026-09-11",
    "notes": null
  },
  {
    "slug": "supabase",
    "name": "Supabase",
    "category": "baas",
    "contracting_entity": "Supabase, Inc.",
    "ultimate_parent": "Supabase, Inc.",
    "parent_jurisdiction": "US",
    "entity_jurisdiction": "US",
    "hosting_regions": [
      "us-east-1",
      "us-west-1",
      "eu-central-1",
      "eu-west-2",
      "ap-southeast-1"
    ],
    "subprocessors": [
      "aws"
    ],
    "eu_alternatives": [
      "eurobase",
      "appwrite"
    ],
    "transfer_mechanism": "SCCs",
    "operational_access_regions": [
      "US",
      "IN"
    ],
    "ratings": {
      "entity_control": "red",
      "data_location": "amber",
      "operational_access": "amber",
      "subprocessor_chain": "amber",
      "transfer_mechanism": "amber",
      "overall": "red"
    },
    "one_line_reason": "Contracting entity Supabase, Inc. is US-incorporated and subject to the CLOUD Act regardless of the EU region configured; runs on AWS as sole hyperscaler subprocessor.\n",
    "sources": [
      "https://supabase.com/docs/guides/platform/data-storage",
      "https://supabase.com/legal/dpa",
      "https://supabase.com/dashboard/org/[org_id]/subprocessors"
    ],
    "last_reviewed": "2026-09-11",
    "notes": null
  },
  {
    "slug": "vercel",
    "name": "Vercel",
    "category": "hosting",
    "contracting_entity": "Vercel Inc.",
    "ultimate_parent": "Vercel Inc.",
    "parent_jurisdiction": "US",
    "entity_jurisdiction": "US",
    "hosting_regions": [
      "iad1",
      "sfo1",
      "fra1",
      "dub1",
      "sin1"
    ],
    "subprocessors": [
      "aws"
    ],
    "eu_alternatives": [
      "scaleway",
      "netlify-eu"
    ],
    "transfer_mechanism": "SCCs",
    "operational_access_regions": [
      "US"
    ],
    "ratings": {
      "entity_control": "red",
      "data_location": "amber",
      "operational_access": "red",
      "subprocessor_chain": "red",
      "transfer_mechanism": "amber",
      "overall": "red"
    },
    "one_line_reason": "Vercel Inc. (US) contracting entity, runs on AWS (US-owned control plane). EU region is available for edge caching but the platform's control plane is US-jurisdictional.\n",
    "sources": [
      "https://vercel.com/legal/dpa",
      "https://vercel.com/legal/subprocessors",
      "https://vercel.com/docs/edge-network/regions"
    ],
    "last_reviewed": "2026-09-11",
    "notes": null
  }
]
